<h1>Panier</h1>
<?php if(count($products)>0): ?>
	<form action="shoppingCart/actualize/" method="post">
		<table>
			<thead>
				<tr>
					<th class="text-left" >Désignation</th>
					<th>prix unitaire TTC</th>
					<th>Quantité</th>
					<th>Sous-total</th>
					<th>Supprimer</th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<th colspan="3" class="text-left">Total</th>
					<th><?= number_format($shoppingCart['totalAmount'], 2, ',', '') ?>€</th>
					<th></th>
				</tr>
			</tfoot>
			<tbody>
			<?php foreach($products as $product):?>
				<tr>
					<td class="text-left"><?= htmlspecialchars($product['name'])?></td>
					<td><?= number_format($product['priceTTC'], 2, ',', ' ')?> €</td>
					<td><input type="number" name="shoppingCart[<?= intval($product['id']) ?>]" value="<?= intval($product['quantity'])?>" maxlength="2" min="1" max="99"></td>
					<td><?= number_format($product['subTotal'],2, ',', ' ')?></td>
					<td><a href="shoppingCart/removeProduct/?id=<?= intval($product['id'])?>" class="button">X</a></td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
		<div class="form_buttons">
			<input type="submit" value="Actualiser" class="button">
			<a href="./" class="button">Continuer mes achats</a>
			<a href="orders/showBillingForm/" class="button">Finaliser ma commande</a>
		</div>
	</form>
<?php else: ?>
	<p>
		Panier vide.
	</p>
<?php endif ?>
