<h1>Récapitulatif de votre commande avant paiement</h1>
<?php if(count($products)>0): ?>
	<h3 class="bleu">Vous avez commandé <?= $shoppingCart['numberOfProducts']?> article<?= $shoppingCart['numberOfProducts']>1 ? 's':null; ?> pour un montant de <?= $shoppingCart['totalAmount']?> euros.</h3>
		<table>
			<thead>
				<tr>
					<th class="text-left" >Désignation</th>
					<th>prix unitaire TTC</th>
					<th>Quantité</th>
					<th>Sous-total</th>
					
				</tr>
			</thead>
			<tfoot>
				<tr>
					<th colspan="3" class="text-left">Total</th>
					<th><?= number_format($shoppingCart['totalAmount'], 2, ',', '') ?>€</th>
				</tr>
			</tfoot>
			<tbody>
			<?php foreach($products as $product):?>
				<tr>
					<td class="text-left"><?= htmlspecialchars($product['name'])?></td>
					<td><?= number_format($product['priceTTC'], 2, ',', ' ')?> €</td>
					<td><?= intval($product['quantity'])?></td>
					<td><?= number_format($product['subTotal'],2, ',', ' ')?></td>	
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
		<div class="payment">
			<h4 class="bleu">Procéder au paiement</h4>
			<a class="payer" href="payment/authenticate/">Payer</a>
		</div>
		
<?php else: ?>
	<p class="rouge">
		Votre panier est vide.
	</p>
<?php endif ?>
