<h1>Identifiez-vous</h1>
<form class="createAccount" action="customers/authenticate/" method="POST">
	<div class="identifiant">
		<label for="username">Adresse email</label>
		<input type="email" name="username" id="username">
	</div>
	<div class="motPasse">
		<label for="password">Mot de passe</label>
		<input type="number" name="password" id="password">
	</div>
	
	
	<!-- <div class="adresse">
		<label for="adresse">Adresse</label>
		<textarea name="adresse" id="adresse" cols="30" rows="3"></textarea>
	</div>
	<div class="codePostal">
		<label for="codePostal">Code postal</label>
		<input type="zip" name="codePostal" Code postal="codePostal">
	</div>
	<div class="commune">
		<label for="commune">Commune</label>
		<input type="text" name="commune" id="commune">
	</div>
	<div class="select">
		<label for="pays">Pays</label>
		<select name="pays" id="pays">
			<option>Choisissez</option>
			<option>France</option>
			<option>Allemagne</option>
			<option>Italie</option>
		</select>
	</div> -->
	<input class="submit" type="submit" value="Envoyer">
</form>
	<a class="authenticate" href="customers/signUp/">Créer un compte</a>